export const SUGGESTION_QUESTIONS = [
  "Why do we fear death if we won't be there to experience it?",
  "Was Socrates right to accept his own death?",
  "Is it rational to grieve someone who no longer exists?",
  "Does knowing you will die make life more or less meaningful?",
  "If death is inevitable, does anything we do actually matter?",
  "Would immortality be a gift or a curse?",
  "Is suicide ever a rational choice?",
  "What did Epicurus mean when he said death is nothing to us?",
  "Did Plato prove the soul is immortal in the Phaedo?",
  "Is Heidegger right that confronting death is the key to authentic life?",
  "Do you actually make choices, or does your brain make them for you?",
  "If everything is determined, can anyone be truly blamed for anything?",
  "Is free will just an illusion we need to function?",
  "Can you be both determined and responsible for your actions?",
  "What is Kant's argument for free will and does it hold?",
  "Did Spinoza believe in free will and was he right?",
  "Is Schopenhauer right that the will drives everything we do?",
  "Is morality discovered or invented?",
  "Can an action be moral if it causes harm?",
  "Is it ever right to lie to protect someone?",
  "Does intention matter more than outcome in moral judgment?",
  "Is there such a thing as pure altruism, or is everything self-interest?",
  "Is morality possible without God?",
  "Do we have moral obligations to people we will never meet?",
  "Is it immoral to be indifferent to suffering you could prevent?",
  "What is Kant's categorical imperative and does it work in practice?",
  "Is Mill's utilitarianism a satisfying moral theory?",
  "Was Aristotle right that virtue is a habit and not a choice?",
  "Is Nietzsche's master morality more honest than Christian morality?",
  "What does the Genealogy of Morals reveal about where our values come from?",
  "Is Machiavelli's ethics a form of realism or just cruelty?",
  "Are you the same person you were ten years ago?",
  "Is there a self, or just a collection of habits and memories?",
  "Can you ever truly know yourself?",
  "If your memories were replaced, would you still be you?",
  "What did Hume mean when he said the self is a bundle of perceptions?",
  "Is Descartes' cogito ergo sum the strongest argument for the self?",
  "Did Nietzsche believe in a stable self or did he reject the idea entirely?",
  "What does Sartre mean when he says we are condemned to be free?",
  "Is there anything you can know for certain?",
  "Can two people look at the same fact and both be right?",
  "Does language shape how we think or just describe it?",
  "Can you trust your own perception of reality?",
  "Is a belief still valid if it makes you happy but is false?",
  "Is science the only valid way to understand the world?",
  "What did Descartes doubt and what did he conclude from it?",
  "Is Plato's theory of Forms a convincing account of reality?",
  "Was Hume right that we can never truly know cause and effect?",
  "What is the difference between knowledge and justified belief?",
  "Is empiricism or rationalism the stronger foundation for knowledge?",
  "What does Kant mean by synthetic a priori knowledge?",
  "Is William James right that truth is whatever works?",
  "Is meaning something you find or something you create?",
  "Can life have meaning without a purpose beyond itself?",
  "Is suffering necessary for a meaningful life?",
  "Can you live meaningfully without believing in anything?",
  "Is ambition a virtue or a disease?",
  "Is boredom a philosophical problem?",
  "What is Aristotle's account of eudaimonia and is it achievable?",
  "Is Camus right that we must imagine Sisyphus happy?",
  "What does Nietzsche mean by the eternal recurrence?",
  "Is the Stoic view of a good life compatible with modern ambition?",
  "Did Schopenhauer think a meaningful life was possible?",
  "Is Kierkegaard right that despair is the universal human condition?",
  "Is civil disobedience ever morally justified?",
  "Do we owe anything to the society that shaped us?",
  "Is democracy the best system or just the least bad one?",
  "Can a just war exist?",
  "Does power always corrupt, or does it just reveal character?",
  "Should individual freedom ever be sacrificed for the common good?",
  "Can a society be just if some of its members suffer greatly?",
  "What is Rousseau's social contract and does it hold today?",
  "Was Hobbes right that without authority life is war?",
  "Is Plato's philosopher king a realistic or dangerous ideal?",
  "What did Machiavelli actually believe about power?",
  "Can you prove God does not exist?",
  "Is faith rational?",
  "Does the existence of evil disprove a benevolent God?",
  "Is atheism just another form of faith?",
  "Can something be sacred without being supernatural?",
  "What is Spinoza's concept of God and how does it differ from religion?",
  "Was Nietzsche's death of God a prophecy or a diagnosis?",
  "Is Pascal's wager a valid argument for belief in God?",
  "What did Kant argue about God and morality?",
  "Is the mind separate from the brain?",
  "Could a machine ever be truly conscious?",
  "Is emotion a weakness or a form of intelligence?",
  "Can reason alone guide a good life?",
  "Are humans fundamentally rational or fundamentally emotional?",
  "What is Descartes' mind-body problem and has it been solved?",
  "Is Hume right that reason is the slave of the passions?",
  "What did Aristotle say the soul actually is?",
  "What did Nietzsche mean when he said God is dead?",
  "Is the will to power a destructive or creative force?",
  "Was Nietzsche a nihilist or the opposite?",
  "What is the Ubermensch and is it an achievable ideal?",
  "Is slave morality still dominant today?",
  "Was Nietzsche right that most people live in herd mentality?",
  "Why did Nietzsche oppose Schopenhauer despite admiring him?",
  "What is Nietzsche's critique of Stoicism in Beyond Good and Evil?",
  "Is Stoic indifference to pain wisdom or repression?",
  "Can you be a Stoic in the modern world?",
  "Is the Stoic acceptance of fate compatible with ambition?",
  "Was Marcus Aurelius a hypocrite for being an emperor and a Stoic?",
  "What is the dichotomy of control and does Epictetus apply it correctly?",
  "Is Stoicism just a sophisticated form of giving up?",
  "What did Seneca say about how to use time well?",
  "What does it mean to live in bad faith?",
  "Is radical freedom a burden or a gift?",
  "Does existence really precede essence?",
  "Is authenticity possible in a world that constantly shapes you?",
  "Is the absurd something to fight or something to embrace?",
  "Was Camus right that the only serious philosophical question is suicide?",
  "What is Kierkegaard's leap of faith and is it rational?",
  "Is Plato's cave still an accurate metaphor for modern life?",
  "Was Plato right that most people mistake shadows for reality?",
  "Is Aristotle's golden mean a useful guide to living?",
  "Can virtue be taught or only practiced?",
  "Is friendship necessary for a good life according to Aristotle?",
  "What is justice according to Plato and is he right?",
  "What is Plato's theory of love in the Symposium?",
  "Did Aristotle improve on Plato or just water him down?",
  "Are most people living lives they never consciously chose?",
  "Do you actually hold the beliefs you think you hold?",
  "Is comfort the enemy of growth?",
  "Do you fear being wrong more than being ignorant?",
] as const;
