export const SUGGESTION_QUESTIONS = [
  "Why do we fear death if we won't be there to experience it?",
  "Was Socrates right to accept his own death?",
  "Is it rational to grieve someone who no longer exists?",
  "Does knowing you will die make life more or less meaningful?",
  "If death is inevitable, does anything we do actually matter?",
  "Would immortality be a gift or a curse?",
  "Is suicide ever a rational choice?",
  "Why do humans create meaning knowing it will end?",
  "Do you actually make choices, or does your brain make them for you?",
  "If everything is determined, can anyone be truly blamed for anything?",
  "Is free will just an illusion we need to function?",
  "Can you be both determined and responsible for your actions?",
  "Does believing in free will make you a better person?",
  "If you could rerun your life identically, would you make the same choices?",
  "Is morality discovered or invented?",
  "Can an action be moral if it causes harm?",
  "Is it ever right to lie to protect someone?",
  "Does intention matter more than outcome in moral judgment?",
  "Can a bad person do a genuinely good thing?",
  "Is there such a thing as pure altruism, or is everything self-interest?",
  "Should you always tell the truth even when it destroys someone?",
  "Is morality possible without God?",
  "Do we have moral obligations to people we will never meet?",
  "Can you be moral without being happy?",
  "Is it immoral to be indifferent to suffering you could prevent?",
  "Does wealth corrupt moral judgment?",
  "Are you the same person you were ten years ago?",
  "Does your past define who you are or just explain it?",
  "Is there a self, or just a collection of habits and memories?",
  "Can you ever truly know yourself?",
  "If your memories were replaced, would you still be you?",
  "Is the person you are in public the real you?",
  "Do you choose your identity or does it choose you?",
  "Is loneliness a sign of depth or a failure to connect?",
  "Is there anything you can know for certain?",
  "Can two people look at the same fact and both be right?",
  "Is ignorance ever a form of happiness worth protecting?",
  "Does language shape how we think or just describe it?",
  "Can you trust your own perception of reality?",
  "Is a belief still valid if it makes you happy but is false?",
  "How do you know your memories are accurate?",
  "Is science the only valid way to understand the world?",
  "Can intuition be trusted as a form of knowledge?",
  "Is meaning something you find or something you create?",
  "Can life have meaning without a purpose beyond itself?",
  "Is the pursuit of happiness a worthy goal?",
  "What makes a life well lived?",
  "Is suffering necessary for a meaningful life?",
  "Can you live meaningfully without believing in anything?",
  "Is ambition a virtue or a disease?",
  "Does a life of comfort lead to a life of meaning?",
  "Is boredom a philosophical problem?",
  "Is civil disobedience ever morally justified?",
  "Do we owe anything to the society that shaped us?",
  "Is democracy the best system or just the least bad one?",
  "Can a just war exist?",
  "Is revolution ever morally justified?",
  "Does power always corrupt, or does it just reveal character?",
  "Should individual freedom ever be sacrificed for the common good?",
  "Is equality of outcome compatible with freedom?",
  "Can a society be just if some of its members suffer greatly?",
  "Is patriotism a virtue or a bias?",
  "Can you prove God does not exist?",
  "Is faith rational?",
  "Does the existence of evil disprove a benevolent God?",
  "Can religion be separated from its historical violence?",
  "Is atheism just another form of faith?",
  "Would the world be more moral without religion?",
  "Can something be sacred without being supernatural?",
  "Is the desire for God a sign of weakness or wisdom?",
  "Is the mind separate from the brain?",
  "Could a machine ever be truly conscious?",
  "Is your inner life visible to anyone but you?",
  "Do animals have moral standing because they can suffer?",
  "Is emotion a weakness or a form of intelligence?",
  "Can reason alone guide a good life?",
  "Is depression a philosophical problem or a medical one?",
  "Are humans fundamentally rational or fundamentally emotional?",
  "What did Nietzsche mean when he said God is dead?",
  "Is the will to power a destructive or creative force?",
  "Was Nietzsche a nihilist or the opposite?",
  "What is the Ubermensch and is it an achievable ideal?",
  "Is slave morality still dominant today?",
  "Was Nietzsche right that most people live in herd mentality?",
  "Is Stoic indifference to pain wisdom or repression?",
  "Can you be a Stoic in the modern world?",
  "Is the Stoic acceptance of fate compatible with ambition?",
  "Was Marcus Aurelius a hypocrite for being an emperor and a Stoic?",
  "Is Stoicism just a sophisticated form of giving up?",
  "What does it mean to live in bad faith?",
  "Is radical freedom a burden or a gift?",
  "Does existence really precede essence?",
  "Can you choose who you are or only what you do?",
  "Is authenticity possible in a world that constantly shapes you?",
  "Is the absurd something to fight or something to embrace?",
  "Was Camus right that the only serious philosophical question is suicide?",
  "Is Plato's cave still an accurate metaphor for modern life?",
  "Was Plato right that most people mistake shadows for reality?",
  "Is Aristotle's golden mean a useful guide to living?",
  "Can virtue be taught or only practiced?",
  "Is friendship necessary for a good life?",
  "What is justice according to Plato and is he right?",
  "Are most people living lives they never consciously chose?",
  "Is the version of yourself others see more real than the one you see?",
  "Do you actually hold the beliefs you think you hold?",
  "Is comfort the enemy of growth?",
  "Are you the hero of your story or a side character in everyone else's?",
  "Is the life you are living the one you would choose if you thought harder?",
  "Do you fear being wrong more than being ignorant?",
  "Is the person you want to be fundamentally different from who you are?",
] as const;
