ALTER TYPE "DebateTone" RENAME VALUE 'RUTHLESS_RESPECTFUL' TO 'RUTHLESS_BLUNT';
ALTER TYPE "DebateTone" RENAME VALUE 'BLUNT_AGGRESSIVE' TO 'SIMPLE_CLEAR';
ALTER TYPE "DebateTone" RENAME VALUE 'TOUGH_POLISHED' TO 'ELITE_INTELLECTUAL_ELEGANT';
